name: deploy-py-layer

on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: 
      name: deploy

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        mkdir python
        python -m pip install --upgrade pip
        pip install -r deployment/requirements.txt -t python/

    - name: Archive Layer content
      run: 
        zip -r layer.zip python/

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Publish Layer
      id: publish_layer
      run: |
        LAYER_VERSION_ARN=$(aws lambda publish-layer-version --layer-name weather_layer --zip-file fileb://layer.zip --compatible-runtimes python3.11 --output text --query 'LayerVersionArn')
        echo "::set-output name=layer_version_arn::$LAYER_VERSION_ARN"