name: deploy-py-lambda

on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: 
      name: deploy

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    
    - name: Deploy code to Lambda
      uses: qubitro/action-lambda-python-zip@v1.0
      with:
        lambda_layer_arn: ${(aws lambda publish-layer-version --layer-name weather_layer --zip-file fileb://layer.zip --compatible-runtimes python3.10 --output text --query 'LayerVersionArn')}
        lambda_function_name: 'generate_weather'
        lambda_region: 'us-east-1'
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
