name: deploy-py-lambda

on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: 
      name: deploy

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Archive code
      run: 
        zip -r ../function.zip .

    - name: Deploy to Lambda
      uses: appleboy/lambda-action@master
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: us-east-1
        function_name: generate_weather
        zip_file: function.zip